changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - major
    - title: New Features 🎉
      labels:
        - minor
        - feature
    - title: Bugfixes
      labels:
        - patch
        - bug
